### ISSUE TITLE
No Javascript in the URL for custom links possible

### ISSUE THREAD

**Issue by FlipZoomMedia** [kongondo/MenuBuilder#17]
I can not save javascript in a custom link in the URL parameter. For example: "javascript:void();". The menu item will not be saved. If I change an existing item, it is removed. The same phenomenon occurs when I leave the URL parameter empty. version 0.1.0

BTW, thanks for the great module.

**Comment by kongondo** [comment]
URL and title are required fields and cannot be left empty (just in case editors forget them). Whereas you can use **#** as a URL, JS will not pass through the sanitizer, i.e. **$sanitizer->url**. That's what's [happening.](https://github.com/kongondo/MenuBuilder/blob/master/ProcessMenuBuilder.module#L1692)
