### ISSUE TITLE
Feature Request: default_class

### ISSUE THREAD

**Issue by jlahijani** [kongondo/MenuBuilder#18]
Although the ability exists to place a custom class on each menu item in the menu builder, there doesn't exist an option to place a **default class** that all items should use.

Here's a good use case.

Let's say I want to output a menu using Bootstrap's List Group component.  Each of the items needs to have the class "list-group-item".

Now also let's say I want to output that same menu but without the "list-group-item" class on the menu items, then I could easily remove it from the options array.

**Comment by kongondo** [comment]
Good idea. I will implement this at the API level (in the $options array).

**Comment by kongondo** [comment]
Added in version 011 in commit 7f0ed12eddc30affb59bb52cb7e1791924a34889 and prior. Thanks.
