### ISSUE TITLE
Feature Request: Display template name and/or URL path when selecting pages

### ISSUE THREAD

**Issue by jlahijani** [kongondo/MenuBuilder#19]
If two pages have the same title, it is impossible to know which page is which when using the ASM Select or Page Auto Complete.

Perhaps display the template name and/or the URL path (in addition to the title) when one chooses pages to add to their menu.

**Comment by kongondo** [comment]
I'll have to think about this one; possibility and feasibility of implementing the feature.

**Comment by kongondo** [comment]
Couldn't find a way to do this via the hook I am using so closing this for now I am afraid.
