### ISSUE TITLE
Feature Request: Alphabetical list of page names for ASM Select

### ISSUE THREAD

**Issue by jlahijani** [kongondo/MenuBuilder#20]
When choosing pages to add to the menu using ASM Select, the list of pages it seems to be in a random order.  Perhaps display them in alphabetical order for ease of use.

**Comment by kongondo** [comment]
Similar to mu response to issue #21, use **sort=title** in the option **Pages selectable in menu **

**Comment by kongondo** [comment]
Closing this issue. Solution is as stated in my comment above.
