### ISSUE TITLE
options for standard class and title

### ISSUE THREAD

**Issue by tobaco** [kongondo/MenuBuilder#24]
it would be nice, if we could have options for a standard class (see #18 ) and for an optional title.
in combination with my pull request ( #23 ) we could use any page field(s) (e.g. a shorter version) for the title output. and if i'm right we would have multilanguage titles out of the box (placeholder {title}).

**Comment by kongondo** [comment]
Multilanguage issues fixed (4d1b015493c54aa60aeda8c22295ac0a909e9afe) and added 'default_class' option as per request #18.
