### ISSUE TITLE
PW3 compatbility: Apply "$m->textFormat = Inputfield::textFormatNone;" accordingly

### ISSUE THREAD

**Issue by jlahijani** [kongondo/MenuBuilder#29]
In some areas of the plugin, you are utilizing HTML in the description field of the InputfieldMarkup.  In more recent versions of PW3, changes were made so that the HTML doesn't get rendered as HTML since it gets entity-ized.  I spoke about it here and included a screenshot of how it affects MenuBuilder:
https://github.com/ryancramerdesign/ProcessWire/issues/1932

The solution is to set the 'textFormat' attribute to 'Inputfield::textFormatNone' on the relevant fields.

**Comment by kferran** [comment]
Thanks @jlahijani for the solution. Been looking at this but didn't fully understand the issue.

**Comment by MichaelvanLaar** [comment]
Fixed the bug using @jlahijani’s suggestion, [see pull request](https://github.com/kongondo/MenuBuilder/pull/30).

**Comment by kongondo** [comment]
Thanks @MichaelvanLaar  and @jlahijani. Fixed in version 16.
