### ISSUE TITLE
Enable/disable an item

### ISSUE THREAD

**Issue by shorty2240** [kongondo/MenuBuilder#33]
Rather than deleting, a possibility to enable/disable (or publish/unpublish) might be a useful feature for a CMS user who wants to temporarily turn off a menu item.

**Comment by kongondo** [comment]
Support added in [version 018](https://github.com/kongondo/MenuBuilder/commit/72b1ee6a1c6fb0a68c1c19cb6fd3eb98909a1bff). Thanks for the suggestion.
