### ISSUE TITLE
PHP Notice: Array to string conversion

### ISSUE THREAD

**Issue by Lazerproof** [kongondo/MenuBuilder#35]
I'm getting 
`PHP Notice: Array to string conversion in ...\ProcessMenuBuilder\MarkupMenuBuilder.module:922`

Possible fix:
Change 
`$menuItems = '';`
to
`$menuItems = array();`
on [this line](https://github.com/kongondo/MenuBuilder/blob/master/MarkupMenuBuilder.module#L915)

**Comment by kongondo** [comment]
Thanks @Lazerproof. This has been resolved in the latest [commit](https://github.com/kongondo/MenuBuilder/commit/342af9186e0675bb9d87aabf797a867384681cd3)
