### ISSUE TITLE
Can't add pages

### ISSUE THREAD

**Issue by tobaco** [kongondo/MenuBuilder#37]
I just installed MenuBuilder in a new Project (PW 3.0.104) with 3 languages (english, german, chinese). 

When I try to add pages via the page selector to the menu, these pages don't get saved and the menu returns empty.

![bildschirmfoto 2018-05-29 um 16 23 26](https://user-images.githubusercontent.com/68937/40665303-2fe4fba4-635d-11e8-9ffd-bfeac8fb57cd.png)
![bildschirmfoto 2018-05-29 um 16 24 20](https://user-images.githubusercontent.com/68937/40665312-34d45e34-635d-11e8-94a6-47f86fc9506c.png)

Custom links get saved without problems.
Pages added with a Processwire selector get added but without names.

![bildschirmfoto 2018-05-29 um 16 29 40](https://user-images.githubusercontent.com/68937/40665562-d14a6e2a-635d-11e8-8ba2-18a81753cd3d.png)

There are no error messages, which could help figure out the problem.

If I delete all languages excluding the default (english) it works as expected.

My setup:

Local Processwire 3.0.104 installation on Mamp
Menu Builder: Process 0.2.3
MySQL 5.6.38
Multilanguage (english, german, chinese)
$config->dbCharset = 'utf8mb4'; (default value)
$config->dbEngine = 'InnoDB'; (default value)

Thanks!

**Comment by tobaco** [comment]
### addendum

If I try to save the empty menu items, which are generated by a selector, they also disappear.
They remain only if I fill in the title field.

**Comment by kongondo** [comment]
I'll have a look @tobaco although I don't have an ETA, am afraid. Wondering if this is specific to this latest version of ProcessWire since MB has been working fine in multi-language environments.

**Comment by tobaco** [comment]
Thanks!
Would be great to see this fixed. It's not a huge issue for me (can use the selector and fill in some titles), but for my future editors, which don't know anything about ProcessWire and selectors and all this stuff.

**Comment by kongondo** [comment]
Hi @tobaco. I cannot replicate the issues. I have tested in a multilingual environment (English, German, Finnish) using PW  3.0.126 and MB 0.2.5. My default language is set to English. I might have resolved the empty names issue in an earlier version, but I can't remember now. 

1. What selector are you using?
2. Maybe you are using a parent path selector that is not resolving properly given you are in a multilingual environment?

**Comment by kongondo** [comment]
Closed as no response received in a while.
