### ISSUE TITLE
Needless echo in buildBreadcrumbs()

### ISSUE THREAD

**Issue by Theominator** [kongondo/MenuBuilder#38]
In MarkupMenuBuilder.module on line 895 is written a `echo $title . '<br>';`, perhaps a leftover from developing. This leads to an faulty output when using renderBreadcrumbs() in conjunction with the option "prepend_home", showing the home title plus a break tag before the real breadcrumb markup.

**Comment by kongondo** [comment]
Thanks for the heads up. Silly mistake on my part. I'll sort it out.

**Comment by kongondo** [comment]
Fixed in latest [commit](https://github.com/kongondo/MenuBuilder/commit/ce103b05feaf6250239fa6fba79faaadd3fa8e21).
