### ISSUE TITLE
apply all "current" classes to li instead of a

### ISSUE THREAD

**Issue by jlahijani** [kongondo/MenuBuilder#4]
Typically, the current class is applied to the li instead of the a element.  Allows for improved styling.

**Comment by dazzyweb** [comment]
Yes it would be better applied to li

**Comment by kongondo** [comment]
They were like that originally but changed to <a> as styles applied to <li> were cascading to sub-menus. OK, will update soon. Will probably put all classes in <li>.

Thanks

**Comment by kongondo** [comment]
[Feature added](https://github.com/kongondo/MenuBuilder/commit/d89a5dfa446cc29591b656f120761b1c1693eeb9) in latest update (0.0.3) including other CSS enhancements (last, first, sub-menu classes, etc).

Thanks.
