### ISSUE TITLE
MenuBuilder permissons not visible in role settings

### ISSUE THREAD

**Issue by digitalbricks** [kongondo/MenuBuilder#40]
As you mentioned in the [module documentation](https://modules.processwire.com/modules/process-menu-builder/), there are serveral permissions for MenuBuilder that could be assigned to roles (such as `menu-builder-lock`, `menu-builder-lock` etc.). But I cannot see such permissions when editing a role – see screenshot attached.
![Bildschirmfoto 2019-04-16 um 10 32 32](https://user-images.githubusercontent.com/2983578/56194672-c2d75000-6033-11e9-8ceb-7d56dc0a1eb2.png)

Or i am just searching at the wrong place?

**Comment by kongondo** [comment]
You must have missed it in the docs or they aren't clear enough :-). All permissions take a whitelist approach. As mentioned in the docs [here](https://github.com/kongondo/MenuBuilder#permissions), you need to create the permissions yourselves and then they will kick in. The only permission created on install is menu-builder.

I'll look into the other issue (#39 ) you reported .

Thanks.

**Comment by digitalbricks** [comment]
Yes – you are so right! I totally missed that (bold written line) in the docs. Actually MenuBuilder is the first module i am using where i have to add the permissions manually – so I didn't think in the right direction. Thank you for pointing me to that!

So you may close this issue :-)
Thank you very much!

**Comment by kongondo** [comment]
No worries.
