### ISSUE TITLE
allow html in title field of menu item

### ISSUE THREAD

**Issue by jlahijani** [kongondo/MenuBuilder#5]
Sometimes it is necessary to put HTML in the title field of a menu item.  For example, let's say you want to put an image or a Font Awesome icon as part of the title (instead of relying on CSS).

WordPress respects HTML inserted in a menu title and outputs it as HTML in the frontend:
http://goo.gl/c14Qq5

MenuBuilder currently strips it out.  The spans in the following image will get stripped upon saving:
http://goo.gl/tyA97p

**Comment by kongondo** [comment]
[Feature added] (https://github.com/kongondo/MenuBuilder/commit/81451902650153d7204117577b46568a941dcacb) (superusers only) in latest version (0.0.3).. 

Note that if you previously saved the menu item titles with Markup and subsequently the menu was edited by a non-supersuser, your markukp will be stripped out upon saving. 

Thanks.

**Comment by kongondo** [comment]
Note: As of version 0.0.4, use of the feature is permission-based (menu-builder-markup). See [ReadMe](https://github.com/kongondo/MenuBuilder#permissions) for details..
